title: Curriculum Vitae
description: Desarrollo Web .Net
author: Luis Delgado Ramírez
github: https://github.com/agusmakmun
about: Desarrollador con 15 años de experiencia, en entorno Web, .Net, integración hardware
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/summonagus"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/agusmakmun"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: About this
      url: /about/
    - text: Tecnologias
      url: /tecnologias
    - text: Educación
      url: /educacion
    - text: Experiencia
      url: /feed.xml
    - text: Proyectos
      url: /projects/    
    - text: Formación
      url: /formacion
    - text: XML Feed
      url: /feed.xml

url: "https://ludelram.github.io"
baseurl: "https://ludelram.github.io/"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
