title: Curriculum Vitae
description: Desarrollo Web .Net
author: Luis Delgado Ramírez
email: ludelram@gmail.com
github: https://github.com/ludelram
about: Ingeniero Técnico de Sistemas. 
       XXX años de experiencia en desarrollo Web .Net.
ano_inicio: 2000
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/Gender_Neutral_User_icon-icons.com_55902.png
cert_url: /static/cert/
# avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    

social:
    - icon: fa-calendar
      text: 1974
    - icon: fa-envelope
      link: mailto:ludelram@gmail.com
      text: ludelram [at] gmail.com
    - icon: fa-car      
      text: Vehículo propio
    - icon: fa-map-marker
      link: https://goo.gl/maps/Fv7xJmdwQVN2
      text: Sevilla, España
    - icon: fa-file-pdf-o
      link: /static/cert/Curriculum Luis Delgado.pdf
      text: Versión PDF
social2:       
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/summonagus"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/ludelram"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: Datos Personales
      url: "#Datos"
    - text: Tecnologías
      url: "#Tecnologias"
    - text: Estudios
      url: "#Estudios"
    - text: Empresas
      url: "#Empresas"
    - text: Cursos
      url: "#Cursos"
    - text: Proyectos
      url: "#Proyectos"    
    - text: Acerca de
      url: "/project/CVitae"    

url: "https://ludelram.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
